#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by Symscape's Caedium on: 23 Apr 2013 19:30:12, www.symscape.com

# Python 2.* compatibility
from __future__ import unicode_literals

import caedium.constant
import caedium.control
import caedium.edit
import caedium.file
import caedium.frm
import caedium.operator
import caedium.select
import caedium.tool.geometry
import caedium.tool.physic
import caedium.tool.result


class Script:
	"""Caedium Script
	"""
	def run(self):
		selection = caedium.select.View(simulation = 'sim', view = 'view', camera = 'camera')
		selection.select()
		tool = caedium.file.NewView()
		tool.addTo(selection)

		selection = caedium.select.View(simulation = 'sim', view = 'view_1', camera = 'camera')
		selection.select(['membrane'])
		property = caedium.frm.Property('Transparent', selection)
		property.appendParent('View')
		property.set(False)

		selection.selectAllEdges()
		property = caedium.frm.Property('Transparent', selection)
		property.appendParent('View')
		property.set(True)

		selection.selectAllAxes()
		property = caedium.frm.Property('Transparent', selection)
		property.appendParent('View')
		property.set(True)

		selection.select()
		tool = caedium.file.Export('membrane-cp.obj', 'obj')
		tool.addTo(selection)

		selection.select(['membrane', 'membrane-shadow'])
		tool = caedium.tool.result.ScalarField('PressureCoefficient')
		tool.addXYPlotTo(selection)

		selection = caedium.select.Plot('Cp Plot')
		selection.select()
		tool = caedium.file.Export('membrane-cp.csv', 'csv')
		tool.addTo(selection)



if __name__ == '__main__':
	caedium.frm.Application.run(Script())
